### ISSUE TITLE
Reported benign validator misbehaviour

### ISSUE THREAD

**Issue by mateuspiresl** [bloxberg-org/bloxbergDocker#1]
I just followed the steps from the README and in the sync process from `run.sh`, after a while, I started to get the following warning repeatedly like a hundred times between each log about the sync process.

```
( the log about the sync process \/ )
Syncing  #976780 0x4629…ced0   129.45 blk/s  324.1 tx/s    9.9 Mgas/s      0+  230 Qed   #977015    2/ 5 peers   331 KiB chain 82 MiB db 803 KiB queue 776 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
( the annoying warning \/ )
2019-03-12 03:27:12 UTC Reported benign validator misbehaviour 0x2fa6…cd53
2019-03-12 03:27:12 UTC Reported benign validator misbehaviour 0xdddc…1f98
... ( a lot of times )
2019-03-12 03:27:12 UTC Reported benign validator misbehaviour 0x2fa6…cd53
2019-03-12 03:27:12 UTC Reported benign validator misbehaviour 0xdddc…1f98
```

It doesn't go away even if I kill and run `run.sh` again.

I don't have any knowledge about parity, so I don't know if it is common or not, but I'm reporting this here so you guys can check.

**Comment by crossoveranx** [comment]
Hi Mateus,

Thanks for the update. This is part of the consensus contracts for bloxberg. Essentially, this is an alert that these addresses have been added to the validator list to confirm blocks, however are offline or non-communicable for whatever reason. The reason behind this is to alert other nodes of possible malicious behavior or downtime.

There are currently two misbehaviors tracked:

- a benign misbehaviour is when a validator does not issue a block.
- a malicious misbehaviour is when a validator tries to create a fork and issues two different blocks for a given step.

It's strange that you are seeing hundreds of these logs as they should be issued only approximately every 10 seconds (about 2 blocks). Is this still occuring after the syncing process?

**Comment by mateuspiresl** [comment]
No. After the sync finished, the warnings appeared as often as you described.

Thank you for the explanation!
