### ISSUE TITLE
Probably wrong rpc port specified

### ISSUE THREAD

**Issue by oleksii-novikov** [bloxberg-org/bloxbergDocker#2]
In `validatorNode.toml` there is next setting:
```
[rpc]
port = 8547
```
At the same time, in `run_prod.sh` and `run.sh`  there is next ports specified:
```
-p 8180:8180 -p 8545:8545 -p 8546:8546 -p 30303:30303
```
So there is no `8547` port, which probably should be there.

As a result, I can't connect to the network using `truffle console --network bloxberg`.
Truffle config is below:
```

  networks: {
    bloxberg: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*"
    }
  },
```
Am I doing something wrong?

**Comment by crossoveranx** [comment]
Hi Oleksii, thanks for the feedback. The reasoning behind this is that this is the configuration for the validator node setup. Generally, we recommend not sending transactions directly from your validator node, as we want to minimize possible attacks to the validator nodes. We suggest for most usecases to setup a separate node to serve transactions. Since Artifacts won't be a validator node in this case, it's perfectly okay to adjust this variable to 8545 which is the default.

As discussed, we need to create a configuration for a bootnode setup as well which will contain different parameters.

As a sidenote, you should also be able to delete the [mining] section as it won't be a mining node, and simply broadcasting transactions to the network.

Please let me know if this answers your question.

**Comment by oleksii-novikov** [comment]
Thanks for the answer!

> As discussed, we need to create a configuration for a bootnode setup as well which will contain different parameters.
Could you please clarify what does it mean?

BTW, here is my current truffle config:
```
module.exports = {
  networks: {
    bloxberg: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*"
    }
  }
};
```

And node config (removed mining section):
```
[parity]
chain = "bloxberg.json"
base_path = "bloxbergData"

[network]
port = 30303
reserved_peers = "./bootnodes.txt"
nat = "91.208.153.1"

[rpc]
disable = false
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "local"

[websockets]
disable = false
port = 8548
interface = "local"
origins = ["none"]

[account]
#CHANGE UNLOCKED ACCOUNT TO YOUR VALIDATOR NODE
unlock = ["0xf1099824***3f59118c83ed8fe2"]
password = ["validatorNode.pwd"]

[footprint]
tracing = "off"
```
When I start node I can see next:
```
Starting Validator Node
Loading config file from validatorNode.toml
2019-05-27 08:04:17 UTC Starting Parity-Ethereum/v2.4.6-stable-94164e1-20190514/x86_64-linux-gnu/rustc1.34.1
2019-05-27 08:04:17 UTC Keys path bloxbergData/keys/Bloxberg
2019-05-27 08:04:17 UTC DB path bloxbergData/chains/Bloxberg/db/60bcf11fadbd7274
2019-05-27 08:04:17 UTC State DB configuration: fast
2019-05-27 08:04:17 UTC Operating mode: active
2019-05-27 08:04:17 UTC Configured for Bloxberg using AuthorityRound engine
2019-05-27 08:04:18 UTC Public node URL: enode://8b46845406f34cf7b0eeeb4f888035850beae5e3486c55233880967538012ff817f29726147b9ebed064767de2f471efaee1fed95eb86f03fcab17a461107789@172.17.0.3:30303
2019-05-27 08:04:18 UTC Listening for new connections on 127.0.0.1:8548.
2019-05-27 08:04:18 UTC Removed existing file 'bloxbergData/jsonrpc.ipc'.
2019-05-27 08:04:28 UTC Syncing snapshot 5/17  #1838326    3/25 peers   81 KiB chain 10 MiB db 0 bytes queue 15 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
```
As I can see, node is listening for WS connections on `127.0.0.1:8548`, but I can't see if it is listening for RPC connections on port `8545` (maybe it is just missing in logs)

When I try to run truffle console I get next error:
```
truffle console --network bloxberg

Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8545
    - network_id > *
```
Do I use the wrong config for bloxberg node? If so, where can I get the right one? Our goal is to set up the node to have an ability to make transactions.
Thanks in advance!

**Comment by crossoveranx** [comment]
This looks correct. I tried it on my machine which is currently running the same configuration (only difference is I have the old 8547 port) and can connect to a truffle console on the bloxberg network:
```
module.exports = {
   networks: {
    development: {
      provider: () =>
        new HDWalletProvider(privKeys, 'https://bloxberg.org/eth/'),
      network_id: '8995'
    },
    bloxberg: {
      host: '127.0.0.1',
      port: 8547,
      network_id: '*'
    }
  }
}
```
Are you able  to see something like when opening a browser and navigating to localhost:8545?:

`Used HTTP Method is not allowed. POST or OPTIONS is required`

If so, then the connection is available on that port.
Are you creating the node and running truffle console on the same machine?


Regarding the configuration for a non-validator node vs validator node is that validator nodes generally require more strict security settings than a bootnode that passes transactions. Therefore, we have to change the parameters a bit when deploying a node only for forwarding transactions.

**Comment by oleksii-novikov** [comment]
> Are you able to see something like when opening a browser and navigating to localhost:8545?:

Unfortunately, when I try to navigate to `localhost:8545` I get `ERR_CONNECTION_RESET The connection was reset.` error.

> Are you creating the node and running truffle console on the same machine?

Yes

It's weird because port `8545` seems to be listen to:
```
netstat -peanut | grep ":8545 "
tcp6       0      0 :::8545                 :::*                    LISTEN      0          3753039    15390/docker-proxy  
```
And `docker ps` returns:
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                            PORTS                                                                                                                              NAMES
5878aed87c25        bloxberg-org/bloxbergdocker   "/parity/scripts/sta…"   5 days ago          Up 7 hours                        5001/tcp, 8080/tcp, 0.0.0.0:8180->8180/tcp, 0.0.0.0:8545-8548->8545-8548/tcp, 8082-8083/tcp, 0.0.0.0:30303->30303/tcp, 30303/udp   brave_knuth
```

**Comment by crossoveranx** [comment]
Hm, strange. Did you rebuild the image after changing the validator config to port 8545?

Another possibility is to also not run it with docker. You can do this by navigating into the config folder and simply running parity --config validatorNode.toml. This will start it manually but not containerized.

**Comment by oleksii-novikov** [comment]
It works ```parity --config validatorNode.toml```. As I can see in logs, the node is synchronizing but I still can't connect either `127.0.0.1:8545` or `truffle console --network bloxberg` using docker.  Will try to take a look more precisely. 
Please let me know if you have some thoughts regarding possible solution

**Comment by oleksii-novikov** [comment]
It looks like I've found the solution by [this](https://github.com/ethereum/go-ethereum/issues/14623#issuecomment-308573542 )
So that `run.sh` as well as `run_prod.sh`:
```
docker run \
  -p 8180:8180 -p 127.0.0.1:8545:8545 -p 8546:8546 -p 30303:30303 \
  -v $DATA_ROOT/bloxbergData:/var/parity \
  -v $DATA_ROOT/config:/parity/config \
  -it $IMG_NAME
```
and there is change in `[rpc]` section in `validatorNode.toml` (`interface` was changed `local` -> `'0.0.0.0'`):
```
[rpc]
disable = false
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "0.0.0.0"
```

Thaks

**Comment by oleksii-novikov** [comment]
Moreover, the only changes that needed are:
- add proper port forwarding in `run.sh` and `run_prod.sh` -> `8545:8545`
- in `[rpc]` section change `interface` from `local` to `0.0.0.0`
